### ISSUE TITLE
Screen Reader Changes 

### ISSUE THREAD

**Issue by eduardo661** [hack4impact-calpoly/go-see-foundation#44]
**Description**
Now that you have first hand experience with the screen reader and some of its shortcomings with the current version of our code, it is time to fix them! This task will be a mix of research, documentation, and coding. Whatever mix of work you want to accomplish is fine. For example, if you don't want to code much, then researching what is causing issues with the screen readers and listing the changes we should make is adequate. On the other hand, if you want spend time fixing the issues hands on, that is also an option!

**Acceptance Criteria**
A google doc highlighting changes made and what they fixed.

Steps:
- step 1: 

**Additional Information**
Do not feel obligated to fixing all issues! If you can't figure something out, go to the next issue.

**Comment by anvch** [comment]
https://docs.google.com/document/d/1c9p18yfdo1ssPH9C2e7Pd9dOQMHKaKv4l9jiUtoa0G8/edit?usp=sharing I've researched the issues and provided articles on possible fixes/changes to make. I can work with implementing these changes for the next sprint, but this is all I could do so far because I was a bit busy the past week.
